repo: mt
wss_url: "wss://mt-eggitorbackend-wangxinglei-user.dev.clock-p.com/ws"
register_ip: "inner-dev.clock-p.com"

bridge:
  wss_url: "wss://mt-eggitorbackend-wangxinglei-user.dev.clock-p.com/ws"

gateway:
  wss_url: "wss://mt-eggitorbackend-wangxinglei-user.dev.clock-p.com/ws"

worker:
  worker_id: "worker-mt"
  http_port: 11115
